media:
  input: images
  output: /images

content:
  - name: index
    label: Home Page
    type: file
    path: index.html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text