ssg: static

paths:
  uploads: "images"
  static: ""

# Automatically make standard HTML tags editable across all pages
_editables:
  content:
    text: true
    hyperlink: true
    image: true

collections_config:
  pages:
    path: ""
    output: true
    filter: "strict"
    glob: "*.html"
    url: "/[slug].html"
    icon: "description"
    name: "Pages"
