# Force CloudCannon to treat the repo as plain HTML
ssg: static

# Set the upload directory for images
paths:
  uploads: "images"
  static: ""

# Define your static HTML pages collection
collections_config:
  pages:
    path: ""
    output: true
    filter: "strict"
    glob: "*.html"
    url: "/[slug].html"
    icon: "description"
    name: "Pages"