ssg: static

paths:
  uploads: "images"
  static: ""

# Enable commit message prompt when saving
commit_templates:
  - template_string: "{message}"
    label: "Describe your changes"


collections_config:
  pages:
    path: ""
    output: true
    filter: "strict"
    glob: "*.html"
    url: "/[slug].html"
    icon: "description"
    name: "Pages"
