backend:
  name: github
  repo: shwetaiyer0/VP2026
  branch: main
  # base_url: https://api.sveltia.dev

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "index.html"
        label: "Home Page (index.html)"
        name: "home_index"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Body Content", name: "body", widget: "code", default_language: "html" }

      - file: "home.html"
        label: "Home Page (home.html)"
        name: "home_page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Body Content", name: "body", widget: "code", default_language: "html" }

      - file: "about.html"
        label: "About Us"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Body Content", name: "body", widget: "code", default_language: "html" }

      - file: "weekly.html"
        label: "Weekly Classes"
        name: "weekly"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Body Content", name: "body", widget: "code", default_language: "html" }

      - file: "happiness.html"
        label: "Happiness Program"
        name: "happiness"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Body Content", name: "body", widget: "code", default_language: "html" }
